apiVersion: v1
kind: Service
metadata:
  name: silksong-frontend
  labels:
    app: silksong-frontend
spec:
  type: LoadBalancer
  # type: ClusterIP
  selector:
    app: silksong-frontend
  ports:
    - name: http
      port: 80
      targetPort: 888
