apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: silksong-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vrouqen/Front-Kubernetes.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default    # o "silksong" si usas namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
