name: build-and-deploy
on:
  push:
    branches: [ "main" ]

jobs:
  build-push-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # para poder commitear el cambio del YAML
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set TAG
        id: vars
        run: echo "TAG=gh-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            vrouqen/front-kubernetes:${{ env.TAG }}

      - name: Bump image tag in k8s/deployment.yaml
        run: |
          sed -i "s#vrouqen/front-kubernetes:.*#vrouqen/front-kubernetes:${TAG}#g" k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "chore(ci): bump image tag to ${TAG}"
          git push
